services:
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=isucon
    - MYSQL_USER=isucon
    - MYSQL_PASSWORD=isucon
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      retries: 100
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql