services:
  app:
    build: .
    ports:
      - 3000:3000
      - 80:80
      - 19999:19999
    volumes:
      - ./50-server.conf:/etc/mysql/mariadb.conf.d/50-server.cnf
      - ./nginx/default.conf:/etc/nginx/sites-available/default
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./config/netdata.conf:/etc/netdata/netdata.conf