services:
  app:
    build: .
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=isucon
    - MYSQL_USER=isucon
    - MYSQL_PASSWORD=isucon
    ports:
      - 3000:3000
      - 80:80
    volumes:
      - ./50-server.conf:/etc/mysql/mariadb.conf.d/50-server.cnf
      - ./nginx/default.conf:/etc/nginx/sites-available/default