services:
  nginx:
    image: nginx:latest
    ports:
      - 3000:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./public:/usr/share/nginx/html/public
  mysql:
    image: mysql:8
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=isucon
    - MYSQL_USER=isucon
    - MYSQL_PASSWORD=isucon
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql